// frontend-angular/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, MatFormFieldModule, MatInputModule, MatButtonModule, MatIconModule, MatProgressSpinnerModule],
  template: `
    <div class="login-container">
      <div class="login-bg">
        <div class="bg-circle c1"></div>
        <div class="bg-circle c2"></div>
        <div class="bg-circle c3"></div>
      </div>
      <div class="login-card">
        <div class="login-header">
          <div class="logo">
            <mat-icon class="logo-icon">school</mat-icon>
          </div>
          <h1>CampusSync</h1>
          <p>CSE Department Admin Portal</p>
        </div>
        <form (ngSubmit)="onLogin()" class="login-form">
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Email</mat-label>
            <input matInput type="email" [(ngModel)]="email" name="email" required>
            <mat-icon matSuffix>email</mat-icon>
          </mat-form-field>
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Password</mat-label>
            <input matInput [type]="showPassword ? 'text' : 'password'" [(ngModel)]="password" name="password" required>
            <mat-icon matSuffix (click)="showPassword = !showPassword" style="cursor:pointer">
              {{showPassword ? 'visibility_off' : 'visibility'}}
            </mat-icon>
          </mat-form-field>
          @if (error) {
            <div class="error-msg">{{error}}</div>
          }
          <button mat-raised-button color="primary" type="submit" class="login-btn" [disabled]="loading">
            @if (loading) { <mat-spinner diameter="20"></mat-spinner> }
            @if (!loading) { <span>Sign In</span> }
          </button>
        </form>
        <div class="login-footer">
          <p>HOD & Lab Incharge Portal</p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .login-container {
      height: 100vh; display: flex; align-items: center; justify-content: center;
      position: relative; overflow: hidden;
      background: linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%);
    }
    .login-bg { position: absolute; inset: 0; z-index: 0; }
    .bg-circle { position: absolute; border-radius: 50%; opacity: 0.1; animation: float 8s infinite ease-in-out; }
    .c1 { width: 400px; height: 400px; background: #00bfa5; top: -100px; left: -100px; }
    .c2 { width: 300px; height: 300px; background: #534bae; bottom: -50px; right: -50px; animation-delay: 2s; }
    .c3 { width: 200px; height: 200px; background: #3b82f6; top: 50%; left: 50%; animation-delay: 4s; }
    @keyframes float { 0%, 100% { transform: translateY(0) scale(1); } 50% { transform: translateY(-20px) scale(1.05); } }
    .login-card {
      background: rgba(26, 35, 50, 0.95); backdrop-filter: blur(20px);
      border: 1px solid rgba(255,255,255,0.1); border-radius: 24px;
      padding: 48px 40px; width: 420px; z-index: 1; box-shadow: 0 24px 48px rgba(0,0,0,0.4);
    }
    .login-header { text-align: center; margin-bottom: 32px; }
    .logo {
      width: 72px; height: 72px; border-radius: 20px;
      background: linear-gradient(135deg, #00bfa5, #5df2d6);
      display: flex; align-items: center; justify-content: center; margin: 0 auto 16px;
    }
    .logo-icon { font-size: 36px; width: 36px; height: 36px; color: #0f1724; }
    h1 { font-size: 28px; font-weight: 700; color: #e2e8f0; margin-bottom: 4px; }
    p { color: #94a3b8; font-size: 14px; }
    .full-width { width: 100%; }
    .login-btn {
      width: 100%; height: 48px; font-size: 16px; font-weight: 600; border-radius: 12px !important;
      margin-top: 8px; background: linear-gradient(135deg, #00bfa5, #5df2d6) !important; color: #0f1724 !important;
    }
    .error-msg {
      color: #ef4444; font-size: 13px; margin-bottom: 8px; text-align: center;
      padding: 8px; background: rgba(239,68,68,0.1); border-radius: 8px;
    }
    .login-footer { text-align: center; margin-top: 24px; }
    .login-footer p { font-size: 12px; color: #64748b; }
    ::ng-deep .login-card .mat-mdc-form-field-subscript-wrapper { display: none; }
  `]
})
export class LoginComponent {
  email = '';
  password = '';
  error = '';
  loading = false;
  showPassword = false;

  constructor(private authService: AuthService, private router: Router) {
    if (this.authService.isLoggedIn) { this.redirectByRole(); }
  }

  onLogin(): void {
    this.error = '';
    this.loading = true;
    this.authService.login(this.email, this.password).subscribe({
      next: () => { this.loading = false; this.redirectByRole(); },
      error: (err) => { this.loading = false; this.error = err.error?.message || 'Login failed.'; }
    });
  }

  private redirectByRole(): void {
    const role = this.authService.userRole;
    if (role === 'hod') this.router.navigate(['/hod/dashboard']);
    else if (role === 'labincharge') this.router.navigate(['/lab/dashboard']);
    else this.error = 'Access denied. This portal is for HOD and Lab Incharge only.';
  }
}

// frontend-react/src/pages/Login.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { HiAcademicCap, HiEye, HiEyeOff } from 'react-icons/hi';

export default function Login() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const [showPw, setShowPw] = useState(false);
    const { login } = useAuth();
    const navigate = useNavigate();

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');
        setLoading(true);
        try {
            const user = await login(email, password);
            if (user.role === 'faculty') navigate('/faculty/dashboard');
            else if (user.role === 'student') navigate('/student/dashboard');
            else { setError('Access denied. This portal is for Students and Faculty only.'); setLoading(false); }
        } catch (err) {
            setError(err.response?.data?.message || 'Login failed');
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center relative overflow-hidden"
            style={{ background: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)' }}>
            {/* Animated bg circles */}
            <div className="absolute w-96 h-96 rounded-full bg-indigo-500/10 -top-24 -left-24 animate-pulse" />
            <div className="absolute w-72 h-72 rounded-full bg-purple-500/10 -bottom-12 -right-12 animate-pulse" style={{ animationDelay: '1s' }} />
            <div className="absolute w-48 h-48 rounded-full bg-cyan-500/10 top-1/2 left-1/2 animate-pulse" style={{ animationDelay: '2s' }} />

            <div className="relative z-10 w-[420px] bg-[#1a2332]/95 backdrop-blur-xl border border-white/10 rounded-3xl p-10 shadow-2xl">
                <div className="text-center mb-8">
                    <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
                        <HiAcademicCap className="text-3xl text-white" />
                    </div>
                    <h1 className="text-2xl font-bold text-gray-100">CampusSync</h1>
                    <p className="text-gray-400 text-sm mt-1">Student & Faculty Portal</p>
                </div>
                <form onSubmit={handleSubmit} className="space-y-4">
                    <div>
                        <label className="label">Email</label>
                        <input type="email" className="input-field" value={email} onChange={e => setEmail(e.target.value)} placeholder="Enter your email" required />
                    </div>
                    <div className="relative">
                        <label className="label">Password</label>
                        <input type={showPw ? 'text' : 'password'} className="input-field pr-10" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter password" required />
                        <button type="button" className="absolute right-3 top-8 text-gray-400 hover:text-gray-200" onClick={() => setShowPw(!showPw)}>
                            {showPw ? <HiEyeOff size={18} /> : <HiEye size={18} />}
                        </button>
                    </div>
                    {error && <div className="text-red-400 text-sm text-center bg-red-500/10 rounded-lg p-2">{error}</div>}
                    <button type="submit" disabled={loading}
                        className="w-full py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl font-semibold hover:from-indigo-500 hover:to-purple-500 transition-all disabled:opacity-50 flex items-center justify-center gap-2">
                        {loading ? <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : 'Sign In'}
                    </button>
                </form>
                <p className="text-center text-gray-500 text-xs mt-6">Student & Faculty Portal</p>
            </div>
        </div>
    );
}
